package henu.soft.epidemicsituationdata.utils;

public class CityUtils {
    public static String[] gn_city = {"北京",
            "天津",
            "上海",
            "重庆",
            "安徽",
            "福建",
            "广东",
            "广西",
            "贵州",
            "甘肃",
            "海南",
            "河南",
            "黑龙江",
            "湖北",
            "湖南",
            "河北",
            "江苏",
            "江西",
            "吉林",
            "辽宁",
            "宁夏",
            "内蒙古",
            "青海",
            "山东",
            "山西",
            "陕西",
            "四川",
            "台湾",
            "西藏",
            "新疆",
            "云南",
            "浙江",
            "香港",
            "澳门"};
}

